In [ ]:
struct tmp
    

In [4]:
a = [[1,2],[3,4]]
b = collect(Base.Flatten(a))

4-element Vector{Int64}:
 1
 2
 3
 4

In [5]:
a = collect(range(1,10))

3

In [15]:
using Random
function create_mini_batches(sample_length::Int64, batch_size::Int64)::Vector{Vector{Int64}}
    ind = shuffle(collect(1:sample_length))
    batch_ind = []
    
    while true
        if length(ind) >= batch_size
            push!(batch_ind, splice!(ind,1:batch_size))
        else
            push!(batch_ind, ind)
            break
        end
    end

    return batch_ind
end

create_mini_batches(10,3)

4-element Vector{Vector{Int64}}:
 [7, 6, 10]
 [1, 5, 4]
 [9, 2, 8]
 [3]

In [27]:
a = transpose(stack([[1,0,1],[ 0,0,1]], dims=1))
[a[:,i][1] for i in 1:size(a,2)]

2-element Vector{Int64}:
 1
 0

In [62]:
using StatsBase: wsample
a = [0,0]
for _ in 1:100
    i = wsample([1,2],[0.2,0.8])
    a[i] += 1
end
a

2-element Vector{Int64}:
 22
 78

In [29]:
using ReinforcementLearning

In [30]:
function step(action,environment)
    s = state(environment)
    environment(action)
    r = reward(environment)

    return s,r
end

e = CartPoleEnv()


# CartPoleEnv

## Traits

| Trait Type        |                  Value |
|:----------------- | ----------------------:|
| NumAgentStyle     |          SingleAgent() |
| DynamicStyle      |           Sequential() |
| InformationStyle  | ImperfectInformation() |
| ChanceStyle       |           Stochastic() |
| RewardStyle       |           StepReward() |
| UtilityStyle      |           GeneralSum() |
| ActionStyle       |     MinimalActionSet() |
| StateStyle        |     Observation{Any}() |
| DefaultStateStyle |     Observation{Any}() |

## Is Environment Terminated?

No

## State Space

`Space{Vector{IntervalSets.ClosedInterval{Float64}}}(IntervalSets.ClosedInterval{Float64}[-4.8..4.8, -Inf..Inf, -0.41887902047863906..0.41887902047863906, -Inf..Inf])`

## Action Space

`Base.OneTo(2)`

## Current State

```
[0.0012086741629943054, 0.03794769958606867, -0.00030351204903651674, 0.01558122573730239]
```


In [75]:
step(1,e)

([-3.5262590062025985, -8.145558791508183, 4.768378491164363, 3.323126227566399], 0.0)

In [23]:
 using StableRNGs, Random
rng = StableRNG(1)  # Set RNG seed globally
function create_mini_batches(
    sample_length::Int64, 
    batch_size::Int64
    )::Vector{Vector{Int64}}

    ind = shuffle(rng,collect(1:sample_length))
    batch_ind = []
    
    while true
        if length(ind) >= batch_size
            push!(batch_ind, splice!(ind,1:batch_size))
        else
            push!(batch_ind, ind)
            break
        end
    end

    return batch_ind
end
# Example usage of create_mini_batches
sample_length = 10
batch_size = 3
batches_1 = create_mini_batches(sample_length, batch_size)  # First call
batches_2 = create_mini_batches(sample_length, batch_size)  # Second call

println(batches_1)  # Should print the same batches
println(batches_2)  # Should also print the same batches

[[9, 2, 7], [8, 1, 6], [10, 5, 3], [4]]
[[3, 4, 9], [2, 10, 7], [5, 8, 6], [1]]


In [24]:
struct t
    s 
end

test = [t(1) for _ in 1:5]

5-element Vector{t}:
 t(1)
 t(1)
 t(1)
 t(1)
 t(1)

In [81]:
log.([0.4081937451196489 0.5834133702493958 0.4153282068228023 0.4081937451196489; 0.5918062548803511 0.4165866297506043 0.5846717931771976 0.5918062548803511])

2×4 Matrix{Float64}:
 -0.896013  -0.538859  -0.878686  -0.896013
 -0.524576  -0.875661  -0.536705  -0.524576

In [13]:
a = [1 1; 2 2]
a

2×2 Matrix{Int64}:
 1  1
 2  2

In [18]:
a[2,:]

2-element Vector{Int64}:
 2
 2

In [7]:
[i for i in [1,2]]

2-element Vector{Int64}:
 1
 2

In [2]:
mutable struct Trajectory
    memory_size ::Int64
    num_states  ::Int64
    num_actions ::Int64
    state       ::Matrix{Float64}
    action      ::Vector{Int64}
    prob        ::Matrix{Float64}
    reward      ::Vector{Float64}
    value       ::Vector{Float64}
    done        ::Vector{Bool}
    advantage   ::Vector{Float64}
    
    function Trajectory(memory_size::Int64, num_states::Int64, num_actions::Int64)
        state     = zeros(Float64, memory_size, num_states)
        action    = zeros(Int64, memory_size)
        prob      = zeros(Float64, memory_size, num_actions)
        reward    = zeros(Float64, memory_size)
        value     = zeros(Float64, memory_size)
        done      = falses(memory_size)
        advantage = zeros(Float64, memory_size)
        new(memory_size, num_states, num_actions, state, action, prob, reward, value, done, advantage)
    end
end

traj = Trajectory(2, 3, 2)
traj.action


2-element Vector{Int64}:
 0
 0

In [6]:
Matrix(transpose(zeros(Bool,2)))

1×2 Matrix{Bool}:
 0  0

In [13]:
a = [1 1; 2 2]
b = [3 3; 4 4]
cat(a,b;dims=1)

4×2 Matrix{Int64}:
 1  1
 2  2
 3  3
 4  4

In [16]:
mutable struct tmp_struct
    i::Int64
end
function change(tmp::tmp_struct)
    tmp.i += 1
end

test = tmp_struct(1)
change(test)

test.i


2

In [17]:
mutable struct Logger    
    Size          ::Int64
    index         ::Int64
    L_entropy     ::Vector{Float64}
    L_value       ::Vector{Float64}
    L_clip        ::Vector{Float64}
    L_total       ::Vector{Float64}     
    kl_divergence ::Vector{Float64}

    function Logger(Size::Int64)
        index         = 1
        L_entropy     = zeros(Float64,Size)
        L_value       = zeros(Float64,Size)
        L_clip        = zeros(Float64,Size)
        L_total       = zeros(Float64,Size)
        kl_divergence = zeros(Float64,Size)  
        new(Size,index,L_value,L_clip,L_total,kl_divergence)
    end
end

l = Logger(3)

MethodError: MethodError: no method matching zeros(::Type{Float64}, ::typeof(size))

Closest candidates are:
  zeros(::Type{T}, !Matched::Union{Integer, AbstractUnitRange}...) where T
   @ Base array.jl:580
  zeros(::Type{T}, !Matched::Tuple{}) where T
   @ Base array.jl:588
  zeros(::Type{T}, !Matched::Tuple{Vararg{Integer, N}}) where {T, N}
   @ Base array.jl:583
  ...
